[package]
name = "gwarell"
version = "0.1.0"
authors = ["Mathieu Moalic <matmoa@pm.me>"]
edition = "2021"

[lib]
name = "gwarell"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module", "abi3-py37"] }
numpy = "0.17"

[workspace]
